---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-throttler
  namespace: kube-throttler
  labels:
    app: kube-throttler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kube-throttler
  template:
    metadata:
      labels:
        app: kube-throttler
    spec:
      serviceAccountName: kube-throttler
      volumes:
      - name: scheduler-config
        configMap:
          name: scheduler-config
      containers:
      - name: ctr
        args:
        - --config=/scheduler-config/config.yaml
        - -v=3
        image: kube-throttler
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: scheduler-config
          mountPath: /scheduler-config

