apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-throttler
resources:
- crd.yaml
- namespace.yaml
- rbac.yaml
- deployment.yaml
configMapGenerator:
- name: scheduler-config
  files:
  - config.yaml
generatorOptions:
  disableNameSuffixHash: true
