apiVersion: v1
kind: ServiceAccount
metadata:
  name: kube-throttler
  namespace: kube-throttler
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: kube-throttler
rules:
- apiGroups: [""]
  resources: ["pods", "namespaces"]
  verbs: ["get","list","watch"]
- apiGroups: ["schedule.k8s.everpeace.github.com"]
  resources: ["clusterthrottles"]
  verbs: ["get","list","watch"]
- apiGroups: ["schedule.k8s.everpeace.github.com"]
  resources: ["clusterthrottles/status"]
  verbs: ["update"]
- apiGroups: ["schedule.k8s.everpeace.github.com"]
  resources: ["throttles"]
  verbs: ["get","list","watch"]
- apiGroups: ["schedule.k8s.everpeace.github.com"]
  resources: ["throttles/status"]
  verbs: ["update"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: kube-throttler
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kube-throttler
subjects:
- kind: ServiceAccount
  namespace: kube-throttler
  name: kube-throttler
