name: CI

on:
  push:
    branches: [ master ]
    tags-ignore: [ "**" ]
    paths-ignore: [ "**.md" ]
  pull_request:
    types: [opened, synchronize]
    paths-ignore: [ "**.md" ]

jobs:

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
    - name: Check out
      uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version-file: 'go.mod'
    - name: Get Devtools
      run: make setup
    - name: Lint
      run : make lint

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - name: Check out
      uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version-file: 'go.mod'
    - name: Get Devtools
      run: make setup
    - name: Build
      run: make build-only
    - name: Test
      run: make test

  integration:
    name: Integration Test
    runs-on: ubuntu-latest
    steps:
    - name: Check out
      uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version-file: 'go.mod'
    - name: Get Devtools
      run: make setup
    - name: integration test
      run: make integration

  validate-goreleaser:
    name: Validate GoReleaser
    runs-on: ubuntu-latest
    steps:
    - name: Check out
      uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version-file: 'go.mod'
    - name: Validate GoReleaser
      uses: goreleaser/goreleaser-action@v2
      with:
        args: release --snapshot --skip-publish --rm-dist --debug
