name: Release
on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  image_build:
    name: Release Docker Image
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    env:
      RELEASE: "true"
      DOCKER_BUILDKIT: 1
      IMAGE_PREFIX: ghcr.io/${{ github.repository_owner }}/
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.16
        id: go
      - name: Check out
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Get Devtools
        run: make setup
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build Docker image
        run: make build-image
      - name: Push Docker image
        run: make push-image

  goreleaser:
    name: Release Binaries
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    env:
      RELEASE: "true"
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ~1.18
        id: go
      - name: Check out
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Get Devtools
        run: make setup
      - name: Get dependencies
        run: go mod download
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  update_release_draft:
    name: Draft Release Note
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    env:
      RELEASE: "true"
    steps:
      - uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
